### ISSUE TITLE
Pants plugin required to run?

### ISSUE THREAD

**Issue by malsharman** [scalameta/fastpass#23]
Have been trying to get the binary to work, but it appears pants needs a plugin "export-fastpass"
Howe do you get this plugin for pants?

**Comment by olafurpg** [comment]
Thank you for reporting! There are no installation instructions since this project is still evolving and it's unclear what the Pants requirements will be (Pants version, Pants plugin, etc). I recommend using the Pants IntelliJ plugin, which is the officially recommended IDE solution for Pants users https://plugins.jetbrains.com/plugin/7412-pants-support/versions

**Comment by olafurpg** [comment]
We just updated the readme and issue template with further details https://github.com/scalameta/fastpass/pull/24
